### ISSUE TITLE
Cannot use container names with periods inside?

### ISSUE THREAD

**Issue by papadeltasierra** [fixpoint/azblob-upload-artifact#26]
I am trying to use this action with the `container` parameter set to `0.0.1` but this seems to trigger this error:

```
Run fixpoint/azblob-upload-artifact@v4
Creating a container "0.0.1" ...
Error: The specifed resource name contains invalid characters.
RequestId:26a16ab-b01e-001b-7129-cad024000000
Time:2023-08-08T18:55:39.8989359Z
Error: The specifed resource name contains invalid characters.
RequestId:26a168ab-b01e-001b-7129-cad024000000
Time:2023-08-08T18:55:39.8989359Z
```
From https://ms./portal.azure.com I can upload files and set the container name (aka folder) to `0.0.1` quite happily.

Any idea why the action cannot create a similar container/folder?

**Comment by papadeltasierra** [comment]
Ok, did some experimenting and I'm very confused.  The Azure portal shows a blob container called `cloudsmets` (I created this).  Now if I upload artifacts...
- and a `container` "cloudsmets" and `name` "0.0.1" then **within** my cloudsmets container I get a `cloudsmets` folder containing a `0.0.1` folder
- with just a `name` I get two folders with the outside being a **sibling** of my cloudsmets blob container; the sibling folder is called `github-actions-artifact` and inside is a folder called `0.0.1`.

So how do I just create the `0.0.1` folder inside the existing blob container?  I want to do this because of course at some point I will create `0.0.2` etc.

I do apologise in advance in case I'm somehow misunderstanding the way that folders work in Azure blob storage.  Is ther something obvious that I'm just doing wrong?

**Comment by papadeltasierra** [comment]
This might help.  I did some command line debugging and this command does exactly what I want, which is:
- Start with an existing container called `cloudsmets`
- Upload a set of files from a source directory
- Place those files in a folder below the existing `cloudsmets` container.

```bash
az storage azcopy blob sync --container cloudsmets --source <my-source-directory> --connection-string <my-connection-string> --destination <my-new-folder>
```

**Comment by lambdalisue** [comment]
I'm not sure if this helps you but the `hello.txt` in `path/to/artifacts` directory will be uploaded as `foo/bar/hello.txt` on `thisiscontainername` container with the following configuration

```yaml
container: "thisiscontainername"
name: "foo/bar"
path: "path/to/artifacts"
```

**Comment by papadeltasierra** [comment]
That is what I would expect so perhaps I managed to get the configuration wrong last night.  I will give it another try tonight.

**Comment by lambdalisue** [comment]
Note that this behaviour is tested in CI (https://github.com/fixpoint/azblob-upload-artifact/actions/runs/5594965806/job/15154834408) so should work I hope.

![CleanShot 2023-08-09 at 23 55 27](https://github.com/fixpoint/azblob-upload-artifact/assets/546312/122b5d25-1524-4f14-bd2f-eeadc2952f4f)

**Comment by papadeltasierra** [comment]
Pleased to report that having carefully checked how I was using your code, it has worked successfully this evening.  I will have to do a little "post mortem" to try and see how I messed up but the code does work as you intended!  Thanks for your patience and advice.
